
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SILLYSLAVE_H
#define SILLYSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SillySlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * SillySlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data SillySlave_Data;
extern UNS8 LifeSignal;		/* Mapped at index 0x2001, subindex 0x00*/

#endif // SILLYSLAVE_H
