
/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;

extern UNS8 DO;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 AO1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 AO2;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 AO3;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 DI;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 AI1;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS8 AI2;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS8 AI3;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS8 AI4;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS8 AI5;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS8 AI6;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS8 AI7;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS8 AI8;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS8 AO4;		/* Mapped at index 0x200D, subindex 0x00*/
