
/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;

extern UNS8 MasterMap1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 MasterMap2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 MasterMap3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 MasterMap4;		/* Mapped at index 0x2003, subindex 0x00*/
