/*
This file is part of CanFestival, a library implementing CanOpen Stack. 

Copyright (C): Edouard TISSERANT and Francis DUPIN

See COPYING file for copyrights details.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

// prototypes of function to be filled by app
void TestMaster_SDOtimeoutError(UNS8 line);
void TestMaster_heartbeatError(UNS8);

UNS8 TestMaster_canSend(Message *);

void TestMaster_initialisation();
void TestMaster_preOperational();
void TestMaster_operational();
void TestMaster_stopped();

void TestMaster_post_sync();
void TestMaster_post_TPDO();

// Master node data struct
extern CO_Data TestMaster_Data;

extern UNS8 MasterMap1;		// Mapped at index 0x2000, subindex 0x00
extern ODCallback_t MasterMap1_callbacks[];		// Callbacks of index0x2000
extern UNS8 MasterMap2;		// Mapped at index 0x2001, subindex 0x00
extern UNS8 MasterMap3;		// Mapped at index 0x2002, subindex 0x00
extern UNS8 MasterMap4;		// Mapped at index 0x2003, subindex 0x00
