/*
This file is part of CanFestival, a library implementing CanOpen Stack. 

Copyright (C): Edouard TISSERANT and Francis DUPIN

See COPYING file for copyrights details.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

// prototypes of function to be filled by app
void TestSlave_SDOtimeoutError(UNS8 line);
void TestSlave_heartbeatError(UNS8);

UNS8 TestSlave_canSend(Message *);

void TestSlave_initialisation();
void TestSlave_preOperational();
void TestSlave_operational();
void TestSlave_stopped();

void TestSlave_post_sync();
void TestSlave_post_TPDO();

// Master node data struct
extern CO_Data TestSlave_Data;

extern UNS8 SlaveMap1;		// Mapped at index 0x2000, subindex 0x00
extern UNS8 SlaveMap2;		// Mapped at index 0x2001, subindex 0x00
extern UNS8 SlaveMap3;		// Mapped at index 0x2002, subindex 0x00
extern UNS8 SlaveMap4;		// Mapped at index 0x2003, subindex 0x00
