
/* File generated by gen_cfile.py. Should not be modified. */

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 win32test_valueRangeTest (UNS8 typeValue, void * value);
const indextable * win32test_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* prototypes of function to be filled by app. */
void win32test_heartbeatError(UNS8);

UNS8 win32test_canSend(Message *);

void win32test_initialisation(void);
void win32test_preOperational(void);
void win32test_operational(void);
void win32test_stopped(void);

void win32test_post_sync(void);
void win32test_post_TPDO(void);

/* Master node data struct */
extern CO_Data win32test_Data;

