
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 gene_SYNC_valueRangeTest (UNS8 typeValue, void * value);
const indextable * gene_SYNC_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data gene_SYNC_Data;
extern UNS16 acceptanceFilter1;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS16 acceptanceFilter2;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 acceptanceFilter3;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 acceptanceFilter4;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 mask1;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 mask2;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS16 mask3;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS16 mask4;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS8 applyDownloadedFilters;		/* Mapped at index 0x2023, subindex 0x00*/

#endif // OBJDICT_H
