/home/epimerde/documents/tc11/CanFestival-3/include/hcs12/candriver.h File Reference
#include <can.h>
#include <objdictdef.h>
Data Structures
struct t_pointerStack
struct canBusTime
struct canBusFilterInit
struct canBusInit
Defines
#define MAX_STACK_MSG_RCV 5
#define NB_LINE_CAN 1
#define CANOPEN_LINE_NUMBER_USED CAN0
Functions
char canAddIdToFilter (UNS16 adrCAN, UNS8 nFilter, UNS16 id)
char canChangeFilter (UNS16 adrCAN, canBusFilterInit fi)
char canEnable (UNS16 adrCAN)
char canInit (UNS16 adrCAN, canBusInit bi)
char canInitClock (UNS16 adrCAN, canBusTime clk)
char canInit1Filter (UNS16 adrCAN, UNS8 nFilter, UNS16 ar, UNS16 mr)
char canInitFilter (UNS16 adrCAN, canBusFilterInit fi)
char canInitMode (UNS16 adrCAN)
char canInitModeQ (UNS16 adrCAN)
char canMsgTransmit (UNS16 adrCAN, Message msg)
char canSetInterrupt (UNS16 adrCAN)
char canSleepMode (UNS16 adrCAN)
char canSleepModeQ (UNS16 adrCAN)
char canSleepWupMode (UNS16 adrCAN)
char canTestInitMode (UNS16 adrCAN)
char canTestSleepMode (UNS16 adrCAN)
Variables
volatile Message stackMsgRcv [NB_LINE_CAN][MAX_STACK_MSG_RCV]
Message msgRcv
volatile t_pointerStack ptrMsgRcv [NB_LINE_CAN]
canBusInit bi
Define Documentation
#define CANOPEN_LINE_NUMBER_USED CAN0
Definition at line 53 of file candriver.h.
#define MAX_STACK_MSG_RCV 5
Definition at line 38 of file candriver.h.
#define NB_LINE_CAN 1
Definition at line 46 of file candriver.h.
Function Documentation
char canAddIdToFilter (UNS16 adrCAN, UNS8 nFilter, UNS16 id)
Definition at line 210 of file canOpenDriver.c.
References CANIDAR0, CANIDAR2, CANIDAR4, CANIDAR6, canTestInitMode(), IO_PORTS_16, IO_PORTS_8, MSG_WAR, and UNS8.
char canChangeFilter (UNS16 adrCAN, canBusFilterInit fi)
Definition at line 250 of file canOpenDriver.c.
References canInitFilter(), canInitMode(), canInitModeQ(), canSetInterrupt(), canSleepMode(), canSleepModeQ(), and canTestInitMode().
char canEnable (UNS16 adrCAN)
Definition at line 266 of file canOpenDriver.c.
References CANCTL1, and IO_PORTS_8.
char canInit (UNS16 adrCAN, canBusInit bi)
Definition at line 277 of file canOpenDriver.c.
References CANCTL0, CANCTL1, canBusInit::cane, canEnable(), canInitClock(), canInitFilter(), canInitMode(), canInitModeQ(), canSetInterrupt(), canSleepMode(), canSleepModeQ(), canTestInitMode(), canBusInit::clk, canBusInit::cswai, canBusInit::fi, IO_PORTS_8, canBusInit::listen, canBusInit::loopb, canBusInit::time, and canBusInit::wupm.
char canInit1Filter (UNS16 adrCAN, UNS8 nFilter, UNS16 ar, UNS16 mr)
Definition at line 335 of file canOpenDriver.c.
References CANIDAR0, CANIDAR2, CANIDAR4, CANIDAR6, canTestInitMode(), IO_PORTS_8, MSG_WAR, and UNS8.
char canInitClock (UNS16 adrCAN, canBusTime clk)
Definition at line 313 of file canOpenDriver.c.
References canBusTime::brp, CANBTR0, CANBTR1, CANCTL1, canTestInitMode(), canBusTime::clksrc, IO_PORTS_8, MSG_WAR, canBusTime::samp, canBusTime::sjw, canBusTime::tseg1, and canBusTime::tseg2.
char canInitFilter (UNS16 adrCAN, canBusFilterInit fi)
Definition at line 364 of file canOpenDriver.c.
References CANIDAC, canBusFilterInit::canidar0, CANIDAR0, canBusFilterInit::canidar1, CANIDAR1, canBusFilterInit::canidar2, CANIDAR2, canBusFilterInit::canidar3, CANIDAR3, canBusFilterInit::canidar4, CANIDAR4, canBusFilterInit::canidar5, CANIDAR5, canBusFilterInit::canidar6, CANIDAR6, canBusFilterInit::canidar7, CANIDAR7, canBusFilterInit::canidmr0, CANIDMR0, canBusFilterInit::canidmr1, CANIDMR1, canBusFilterInit::canidmr2, CANIDMR2, canBusFilterInit::canidmr3, CANIDMR3, canBusFilterInit::canidmr4, CANIDMR4, canBusFilterInit::canidmr5, CANIDMR5, canBusFilterInit::canidmr6, CANIDMR6, canBusFilterInit::canidmr7, CANIDMR7, canTestInitMode(), canBusFilterInit::idam, IO_PORTS_8, and MSG_WAR.
char canInitMode (UNS16 adrCAN)
Definition at line 392 of file canOpenDriver.c.
References CANCTL0, canTestInitMode(), and IO_PORTS_8.
char canInitModeQ (UNS16 adrCAN)
Definition at line 401 of file canOpenDriver.c.
References CANCTL0, canTestInitMode(), and IO_PORTS_8.
char canMsgTransmit (UNS16 adrCAN, Message msg)
Definition at line 410 of file canOpenDriver.c.
References CANTBSEL, CANTFLG, CANTRSDTA, CANTRSID, CANTRSLEN, CANTRSPRI, Message::cob_id, Message::data, IO_PORTS_8, Message::len, MSG_WAR, Message::rtr, UNS8, and SHORT_CAN::w.
char canSetInterrupt (UNS16 adrCAN)
Definition at line 445 of file canOpenDriver.c.
References CANRIER, CANTIER, and IO_PORTS_8.
char canSleepMode (UNS16 adrCAN)
Definition at line 452 of file canOpenDriver.c.
References CANCTL0, canTestSleepMode(), and IO_PORTS_8.
char canSleepModeQ (UNS16 adrCAN)
Definition at line 466 of file canOpenDriver.c.
References CANCTL0, canTestInitMode(), canTestSleepMode(), IO_PORTS_8, and MSG_WAR.
char canSleepWupMode (UNS16 adrCAN)
Definition at line 480 of file canOpenDriver.c.
References CANCTL0, canTestInitMode(), canTestSleepMode(), IO_PORTS_8, and MSG_WAR.
char canTestInitMode (UNS16 adrCAN)
Definition at line 493 of file canOpenDriver.c.
References CANCTL1, and IO_PORTS_8.
char canTestSleepMode (UNS16 adrCAN)
Definition at line 499 of file canOpenDriver.c.
References CANCTL1, and IO_PORTS_8.
Variable Documentation
canBusInit bi
Message msgRcv
volatile t_pointerStack ptrMsgRcv[NB_LINE_CAN]
volatile Message stackMsgRcv[NB_LINE_CAN][MAX_STACK_MSG_RCV]