/home/epimerde/documents/tc11/CanFestival-3/include/hcs12/canOpenDriver.h File Reference
Functions
void initTimer (void)
void resetTimer (void)
void TimerLoop (void)
UNS8 f_can_receive (UNS8 notused, Message *m)
Function Documentation
UNS8 f_can_receive (UNS8 notused, Message * m)
Returns 0 if no message received, 0xFF if the receiving stack is not empty. May be call in polling. You can also call canDispatch(...) in void __attribute__((interrupt)) can0HdlRcv (void) (see include/hcs12/canOpenDriver.c)
void initTimer (void)
Definition at line 79 of file canOpenDriver.c.
References IO_PORTS_8, last_sig, lock(), TCTL1, TIE, timer, timer_notify(), TIOS, TSCR1, TSCR2, and unlock().
void resetTimer (void)
Definition at line 73 of file canOpenDriver.c.
void TimerLoop (void)