can_uvccm_win32 Class Reference
Public Member Functions
can_uvccm_win32 (s_BOARD *board)
~can_uvccm_win32 ()
bool send (const Message *m)
bool receive (Message *m)
Private Member Functions
bool open_rs232 (int port=1, int baud_rate=57600)
bool close_rs232 ()
bool get_can_data (const char *can_cmd_buf, long &bufsize, Message *m)
bool set_can_data (const Message &m, std::string &can_cmd)
Private Attributes
HANDLE m_port
HANDLE m_read_event
HANDLE m_write_event
std::string m_residual_buffer
Data Structures
class error
Detailed Description
Definition at line 17 of file can_uvccm_win32.cpp.
Constructor & Destructor Documentation
can_uvccm_win32::can_uvccm_win32 (s_BOARD * board)
Definition at line 39 of file can_uvccm_win32.cpp.
References struct_s_BOARD::baudrate, and open_rs232().
can_uvccm_win32::~can_uvccm_win32 ()
Definition at line 47 of file can_uvccm_win32.cpp.
References close_rs232().
Member Function Documentation
bool can_uvccm_win32::send (const Message * m)
Definition at line 52 of file can_uvccm_win32.cpp.
References FALSE, m_port, m_write_event, set_can_data(), and eds_utils::WriteFile().
bool can_uvccm_win32::receive (Message * m)
Definition at line 80 of file can_uvccm_win32.cpp.
References FALSE, get_can_data(), m_port, m_read_event, and m_residual_buffer.
bool can_uvccm_win32::open_rs232 (int port = 1, int baud_rate = 57600) [private]
Definition at line 136 of file can_uvccm_win32.cpp.
References FALSE, m_port, m_read_event, m_write_event, and TRUE.
bool can_uvccm_win32::close_rs232 () [private]
Definition at line 190 of file can_uvccm_win32.cpp.
References m_port, m_read_event, m_residual_buffer, and m_write_event.
bool can_uvccm_win32::get_can_data (const char * can_cmd_buf, long & bufsize, Message * m) [private]
Definition at line 206 of file can_uvccm_win32.cpp.
References Message::cob_id, Message::data, Message::len, Message::rtr, UNS8, and SHORT_CAN::w.
bool can_uvccm_win32::set_can_data (const Message & m, std::string & can_cmd) [private]
Definition at line 271 of file can_uvccm_win32.cpp.
References Message::cob_id, Message::data, Message::len, Message::rtr, and SHORT_CAN::w.
Field Documentation
HANDLE can_uvccm_win32::m_port [private]
Definition at line 33 of file can_uvccm_win32.cpp.
HANDLE can_uvccm_win32::m_read_event [private]
Definition at line 34 of file can_uvccm_win32.cpp.
HANDLE can_uvccm_win32::m_write_event [private]
Definition at line 35 of file can_uvccm_win32.cpp.
std::string can_uvccm_win32::m_residual_buffer [private]
Definition at line 36 of file can_uvccm_win32.cpp.
The documentation for this class was generated from the following file:
/home/epimerde/documents/tc11/CanFestival-3/drivers/can_uvccm_win32/can_uvccm_win32.cpp