class_timers Class Reference
Public Member Functions
class_timers ()
~class_timers ()
void start_timer_thread ()
void resume_timer_thread ()
void stop_timer_thread ()
void set_timer (TIMEVAL value)
TIMEVAL get_elapsed_time ()
Private Member Functions
TIMEVAL get_timer () const
Static Private Member Functions
static DWORD WINAPI timer_loop_thread_proc (void *arg)
Private Attributes
TIMEVAL m_last_occured_alarm_time
volatile TIMEVAL m_last_alarm_set_time
HANDLE m_timer_thread
volatile bool m_continue_timer_loop
bool m_use_hi_res_timer
double m_counts_per_usec
Detailed Description
Definition at line 94 of file timers_win32.cpp.
Constructor & Destructor Documentation
class_timers::class_timers ()
Definition at line 116 of file timers_win32.cpp.
References m_counts_per_usec, and m_use_hi_res_timer.
class_timers::~class_timers ()
Definition at line 133 of file timers_win32.cpp.
References stop_timer_thread().
Member Function Documentation
void class_timers::start_timer_thread ()
Definition at line 173 of file timers_win32.cpp.
References get_timer(), m_last_alarm_set_time, m_last_occured_alarm_time, m_timer_thread, timer_loop_thread_proc(), and TIMEVAL_MAX.
void class_timers::resume_timer_thread ()
Definition at line 184 of file timers_win32.cpp.
References m_continue_timer_loop, and m_timer_thread.
void class_timers::stop_timer_thread ()
Definition at line 193 of file timers_win32.cpp.
References m_continue_timer_loop, and m_timer_thread.
void class_timers::set_timer (TIMEVAL value)
Definition at line 204 of file timers_win32.cpp.
References get_timer(), m_last_alarm_set_time, and TIMEVAL_MAX.
TIMEVAL class_timers::get_elapsed_time ()
Definition at line 210 of file timers_win32.cpp.
References get_timer(), and m_last_occured_alarm_time.
TIMEVAL class_timers::get_timer () const [private]
Definition at line 139 of file timers_win32.cpp.
References m_counts_per_usec, m_use_hi_res_timer, and TIMEVAL.
DWORD WINAPI class_timers::timer_loop_thread_proc (void * arg) [static, private]
Definition at line 151 of file timers_win32.cpp.
References EnterMutex(), get_timer(), LeaveMutex(), m_continue_timer_loop, m_last_alarm_set_time, m_last_occured_alarm_time, TimeDispatch(), TIMEVAL, and TIMEVAL_MAX.
Field Documentation
TIMEVAL class_timers::m_last_occured_alarm_time [private]
Definition at line 108 of file timers_win32.cpp.
volatile TIMEVAL class_timers::m_last_alarm_set_time [private]
Definition at line 109 of file timers_win32.cpp.
HANDLE class_timers::m_timer_thread [private]
Definition at line 110 of file timers_win32.cpp.
volatile bool class_timers::m_continue_timer_loop [private]
Definition at line 111 of file timers_win32.cpp.
bool class_timers::m_use_hi_res_timer [private]
Definition at line 112 of file timers_win32.cpp.
double class_timers::m_counts_per_usec [private]
Definition at line 113 of file timers_win32.cpp.
The documentation for this class was generated from the following file:
/home/epimerde/documents/tc11/CanFestival-3/drivers/win32/timers_win32.cpp