/home/epimerde/documents/tc11/CanFestival-3/src/dcf.c File Reference
#include `objacces.h`
#include `sdo.h`
#include `dcf.h`
#include `sysdep.h`
Functions
UNS8 _writeNetworkDict (CO_Data *d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 count, UNS8 dataType, void *data, SDOCallback_t Callback, UNS8 endianize)
UNS32 decompo_dcf (CO_Data *d, UNS8 nodeId)
Variables
const indextable * ptrTable
Function Documentation
INLINE UNS8 _writeNetworkDict (CO_Data * d, UNS8 nodeId, UNS16 index, UNS8 subIndex, UNS8 count, UNS8 dataType, void * data, SDOCallback_t Callback, UNS8 endianize)
Definition at line 1072 of file sdo.c.
References getSDOfreeLine(), getSDOlineOnUse(), initSDOline(), resetSDOline(), and sendSDO().
UNS32 decompo_dcf (CO_Data * d, UNS8 nodeId)
Definition at line 49 of file dcf.c.
References _writeNetworkDict(), and ptrTable.
Variable Documentation
const indextable* ptrTable
Definition at line 33 of file dcf.c.