/home/epimerde/documents/tc11/CanFestival-3/drivers/win32/drivers_win32.cpp File Reference
#include <windows.h>
#include `canfestival.h`
#include `timer.h`
#include `timers_driver.h`
Data Structures
class driver_procs
struct driver_data
Defines
#define DLL_CALL(funcname) (*_##funcname)
#define FCT_PTR_INIT =NULL
#define myTEXT(str) str
Typedefs
typedef UNS8(*) CANRECEIVE_DRIVER_PROC (void *inst, Message *m)
typedef UNS8(*) CANSEND_DRIVER_PROC (void *inst, const Message *m)
typedef void *(*) CANOPEN_DRIVER_PROC (s_BOARD *board)
typedef int(*) CANCLOSE_DRIVER_PROC (void *inst)
Functions
LIB_HANDLE LoadCanDriver (char *driver_name)
UNS8 canReceive (CAN_PORT fd0, Message *m)
void * canReceiveLoop (CAN_PORT fd0)
UNS8 canSend (CAN_PORT fd0, Message *m)
CAN_HANDLE canOpen (s_BOARD *board, CO_Data *d)
int canClose (CO_Data *d)
Variables
driver_procs s_driver_procs
Define Documentation
#define DLL_CALL(funcname) (*_##funcname)
Definition at line 32 of file drivers_win32.cpp.
#define FCT_PTR_INIT =NULL
Definition at line 33 of file drivers_win32.cpp.
#define myTEXT(str) str
Definition at line 91 of file drivers_win32.cpp.
Typedef Documentation
typedef int(*) CANCLOSE_DRIVER_PROC(void *inst)
Definition at line 43 of file drivers_win32.cpp.
typedef void*(*) CANOPEN_DRIVER_PROC(s_BOARD *board)
Definition at line 42 of file drivers_win32.cpp.
typedef UNS8(*) CANRECEIVE_DRIVER_PROC(void *inst, Message *m)
Definition at line 40 of file drivers_win32.cpp.
typedef UNS8(*) CANSEND_DRIVER_PROC(void *inst, const Message *m)
Definition at line 41 of file drivers_win32.cpp.
Function Documentation
int canClose (CO_Data * d)
Definition at line 194 of file drivers_win32.cpp.
References canClose(), struct_CO_Data::canHandle, driver_data::continue_receive_thread, DLL_CALL, EnterMutex(), CANPort::fd, driver_data::inst, LeaveMutex(), driver_procs::m_canClose, driver_data::receive_thread, CANPort::receiveTask, s_driver_procs, and WaitReceiveTaskEnd().
CAN_HANDLE canOpen (s_BOARD * board, CO_Data * d)
Definition at line 172 of file drivers_win32.cpp.
References struct_s_BOARD::baudrate, struct_s_BOARD::busname, struct_CO_Data::canHandle, canOpen(), canports, canReceiveLoop(), driver_data::continue_receive_thread, CreateReceiveTask(), CANPort::d, driver_data::d, DLL_CALL, EnterMutex(), CANPort::fd, driver_data::inst, LeaveMutex(), driver_procs::m_canOpen, MAX_NB_CAN_PORTS, driver_data::receive_thread, s_driver_procs, and CANPort::used.
UNS8 canReceive (CAN_PORT fd0, Message * m)
Definition at line 124 of file drivers_win32.cpp.
References driver_data::inst, driver_procs::m_canReceive, and s_driver_procs.
void* canReceiveLoop (CAN_PORT fd0)
Definition at line 134 of file drivers_win32.cpp.
References canDispatch(), canReceive(), driver_data::continue_receive_thread, driver_data::d, EnterMutex(), and LeaveMutex().
UNS8 canSend (CAN_PORT fd0, Message * m)
Definition at line 156 of file drivers_win32.cpp.
References canSend(), DLL_CALL, EnterMutex(), driver_data::inst, LeaveMutex(), driver_procs::m_canSend, s_driver_procs, and UNS8.
LIB_HANDLE LoadCanDriver (char * driver_name)
Definition at line 119 of file drivers_win32.cpp.
References canClose(), canOpen(), canReceive(), canSend(), DLSYM, driver_procs::load_canfestival_driver(), and s_driver_procs.
Variable Documentation
driver_procs s_driver_procs
Definition at line 117 of file drivers_win32.cpp.