/home/epimerde/documents/tc11/CanFestival-3/src/lifegrd.c File Reference
#include <data.h>
#include `lifegrd.h`
#include `canfestival.h`
Functions
void ConsumerHearbeatAlarm (CO_Data *d, UNS32 id)
void ProducerHearbeatAlarm (CO_Data *d, UNS32 id)
UNS32 OnHearbeatProducerUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
e_nodeState getNodeState (CO_Data *d, UNS8 nodeId)
void proceedNODE_GUARD (CO_Data *d, Message *m)
UNS32 OnHeartbeatProducerUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
void heartbeatInit (CO_Data *d)
void heartbeatStop (CO_Data *d)
void _heartbeatError (UNS8 heartbeatID)
Function Documentation
void _heartbeatError (UNS8 heartbeatID)
Definition at line 184 of file lifegrd.c.
void ConsumerHearbeatAlarm (CO_Data * d, UNS32 id)
Definition at line 41 of file lifegrd.c.
e_nodeState getNodeState (CO_Data * d, UNS8 nodeId)
Definition at line 33 of file lifegrd.c.
void heartbeatInit (CO_Data * d)
Definition at line 147 of file lifegrd.c.
References ConsumerHearbeatAlarm(), OnHeartbeatProducerUpdate(), ProducerHearbeatAlarm(), RegisterSetODentryCallBack(), and SetAlarm().
void heartbeatStop (CO_Data * d)
Definition at line 173 of file lifegrd.c.
References DelAlarm().
UNS32 OnHearbeatProducerUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
UNS32 OnHeartbeatProducerUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
Definition at line 139 of file lifegrd.c.
References heartbeatInit(), and heartbeatStop().
void proceedNODE_GUARD (CO_Data * d, Message * m)
Definition at line 50 of file lifegrd.c.
References ConsumerHearbeatAlarm(), DelAlarm(), and SetAlarm().
void ProducerHearbeatAlarm (CO_Data * d, UNS32 id)
Definition at line 113 of file lifegrd.c.
References DelAlarm().