/home/epimerde/documents/tc11/CanFestival-3/include/nmtMaster.h File Reference
#include `data.h`
Functions
UNS8 masterSendNMTstateChange (CO_Data *d, UNS8 Node_ID, UNS8 cs)
UNS8 masterSendNMTnodeguard (CO_Data *d, UNS8 nodeId)
void masterRequestNodeState (CO_Data *d, UNS8 nodeId)
Function Documentation
void masterRequestNodeState (CO_Data * d, UNS8 nodeId)
Prepare a Node_Guard message transmission on the bus number bus_id to the slave whose node_id is nodeId Put nodeId = 0 to send an NMT broadcast. This message will ask for the slave, whose node_id is nodeId, its state bus_id is hardware dependant
Definition at line 60 of file nmtMaster.c.
References struct_s_timer_entry::d, masterSendNMTnodeguard(), NMT_MAX_NODE_ID, struct_CO_Data::NMTable, Unknown_state, and UNS8.
UNS8 masterSendNMTnodeguard (CO_Data * d, UNS8 nodeId)
Transmit a Node_Guard message on the bus number bus_id to the slave whose node_id is nodeId bus_id is hardware dependant return canSend(bus_id,&m)
Definition at line 45 of file nmtMaster.c.
References struct_CO_Data::canHandle, canSend(), Message::cob_id, struct_s_timer_entry::d, Message::len, MSG_WAR, NODE_GUARD, REQUEST, Message::rtr, and SHORT_CAN::w.
UNS8 masterSendNMTstateChange (CO_Data * d, UNS8 Node_ID, UNS8 cs)
Transmit a NMT message on the bus number bus_id to the slave whose node_id is ID bus_id is hardware dependant cs represents the order of state changement: cs = NMT_Start_Node // Put the node in operational mode cs = NMT_Stop_Node // Put the node in stopped mode cs = NMT_Enter_PreOperational // Put the node in pre_operational mode cs = NMT_Reset_Node // Put the node in initialization mode cs = NMT_Reset_Comunication // Put the node in initialization mode The mode is changed according to the slave state machine mode : initialisation ---> pre-operational (Automatic transition) pre-operational <--> operational pre-operational <--> stopped pre-operational, operational, stopped -> initialisation
return canSend(bus_id,&m)
Definition at line 27 of file nmtMaster.c.
References struct_CO_Data::canHandle, canSend(), Message::cob_id, struct_s_timer_entry::d, Message::data, Message::len, MSG_WAR, NOT_A_REQUEST, Message::rtr, and SHORT_CAN::w.