/home/epimerde/documents/tc11/CanFestival-3/include/objacces.h File Reference
Responsible for accessing the object dictionary.
#include <applicfg.h>
#include `data.h`
Typedefs
typedef UNS32(*) valueRangeTest_t (UNS8 typeValue, void *Value)
typedef void(*) storeODSubIndex_t (UNS16 wIndex, UNS8 bSubindex)
Functions
void _storeODSubIndex (UNS16 wIndex, UNS8 bSubindex)
UNS8 accessDictionaryError (UNS16 index, UNS8 subIndex, UNS8 sizeDataDict, UNS8 sizeDataGiven, UNS32 code)
UNS32 getODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pDestData, UNS8 *pExpectedSize, UNS8 *pDataType, UNS8 checkAccess)
UNS32 setODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pSourceData, UNS8 *pExpectedSize, UNS8 checkAccess)
UNS32 writeLocalDict (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pSourceData, UNS8 *pExpectedSize, UNS8 checkAccess)
const indextable * scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 *errorCode, ODCallback_t **Callback)
UNS32 RegisterSetODentryCallBack (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
Detailed Description
Responsible for accessing the object dictionary.
This file contains functions for accessing the object dictionary and variables that are contained by the object dictionary. Accessing the object dictionary contains setting local variables as PDOs and accessing (read/write) all entries of the object dictionary
Warning: Only the basic entries of an object dictionary are included at the moment.
Definition in file objacces.h.
Typedef Documentation
typedef void(*) storeODSubIndex_t(UNS16 wIndex, UNS8 bSubindex)
Definition at line 40 of file objacces.h.
typedef UNS32(*) valueRangeTest_t(UNS8 typeValue, void *Value)
Definition at line 39 of file objacces.h.
Function Documentation
void _storeODSubIndex (UNS16 wIndex, UNS8 bSubindex)
Definition at line 308 of file objacces.c.
UNS8 accessDictionaryError (UNS16 index, UNS8 subIndex, UNS8 sizeDataDict, UNS8 sizeDataGiven, UNS32 code)
Definition at line 31 of file objacces.c.
References MSG_WAR, OD_LENGTH_DATA_INVALID, OD_NO_SUCH_OBJECT, OD_NO_SUCH_SUBINDEX, OD_NOT_MAPPABLE, OD_VALUE_TOO_HIGH, OD_VALUE_TOO_LOW, and OD_WRITE_NOT_ALLOWED.
UNS32 getODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pDestData, UNS8 * pExpectedSize, UNS8 * pDataType, UNS8 checkAccess)
Definition at line 145 of file objacces.c.
References _getODentry(), and struct_s_timer_entry::d.
UNS32 RegisterSetODentryCallBack (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
Definition at line 297 of file objacces.c.
References struct_s_timer_entry::d, OD_SUCCESSFUL, scanIndexOD(), and UNS32.
const indextable* scanIndexOD (CO_Data * d, UNS16 wIndex, UNS32 * errorCode, ODCallback_t ** Callback)
Definition at line 292 of file objacces.c.
References struct_s_timer_entry::d, and struct_CO_Data::scanIndexOD.
UNS32 setODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pSourceData, UNS8 * pExpectedSize, UNS8 checkAccess)
Definition at line 257 of file objacces.c.
References _setODentry(), and struct_s_timer_entry::d.
UNS32 writeLocalDict (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pSourceData, UNS8 * pExpectedSize, UNS8 checkAccess)
Definition at line 273 of file objacces.c.
References _setODentry(), and struct_s_timer_entry::d.