/home/epimerde/documents/tc11/CanFestival-3/src/objacces.c File Reference
#include `objacces.h`
Functions
UNS8 accessDictionaryError (UNS16 index, UNS8 subIndex, UNS8 sizeDataDict, UNS8 sizeDataGiven, UNS32 code)
UNS32 _getODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pDestData, UNS8 *pExpectedSize, UNS8 *pDataType, UNS8 checkAccess, UNS8 endianize)
UNS32 getODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pDestData, UNS8 *pExpectedSize, UNS8 *pDataType, UNS8 checkAccess)
UNS32 readLocalDict (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pDestData, UNS8 *pExpectedSize, UNS8 *pDataType, UNS8 checkAccess)
UNS32 _setODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pSourceData, UNS8 *pExpectedSize, UNS8 checkAccess, UNS8 endianize)
UNS32 setODentry (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pSourceData, UNS8 *pExpectedSize, UNS8 checkAccess)
UNS32 writeLocalDict (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, void *pSourceData, UNS8 *pExpectedSize, UNS8 checkAccess)
const indextable * scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 *errorCode, ODCallback_t **Callback)
UNS32 RegisterSetODentryCallBack (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
void _storeODSubIndex (UNS16 wIndex, UNS8 bSubindex)
Function Documentation
UNS32 _getODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pDestData, UNS8 * pExpectedSize, UNS8 * pDataType, UNS8 checkAccess, UNS8 endianize)
Definition at line 68 of file objacces.c.
References accessDictionaryError(), and ptrTable.
UNS32 _setODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pSourceData, UNS8 * pExpectedSize, UNS8 checkAccess, UNS8 endianize)
Definition at line 181 of file objacces.c.
References accessDictionaryError(), and ptrTable.
void _storeODSubIndex (UNS16 wIndex, UNS8 bSubindex)
Definition at line 308 of file objacces.c.
UNS8 accessDictionaryError (UNS16 index, UNS8 subIndex, UNS8 sizeDataDict, UNS8 sizeDataGiven, UNS32 code)
Definition at line 31 of file objacces.c.
UNS32 getODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pDestData, UNS8 * pExpectedSize, UNS8 * pDataType, UNS8 checkAccess)
Definition at line 145 of file objacces.c.
References _getODentry().
UNS32 readLocalDict (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pDestData, UNS8 * pExpectedSize, UNS8 * pDataType, UNS8 checkAccess)
Definition at line 163 of file objacces.c.
References _getODentry().
UNS32 RegisterSetODentryCallBack (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
Definition at line 297 of file objacces.c.
References scanIndexOD().
const indextable* scanIndexOD (CO_Data * d, UNS16 wIndex, UNS32 * errorCode, ODCallback_t ** Callback)
Definition at line 292 of file objacces.c.
UNS32 setODentry (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pSourceData, UNS8 * pExpectedSize, UNS8 checkAccess)
Definition at line 257 of file objacces.c.
References _setODentry().
UNS32 writeLocalDict (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, void * pSourceData, UNS8 * pExpectedSize, UNS8 checkAccess)
Definition at line 273 of file objacces.c.
References _setODentry().