/home/epimerde/documents/tc11/CanFestival-3/src/pdo.c File Reference
#include `pdo.h`
#include `objacces.h`
#include `canfestival.h`
Functions
UNS8 sendPDO (CO_Data *d, s_PDO pdo, UNS8 req)
UNS8 PDOmGR (CO_Data *d, UNS32 cobId)
UNS8 sendPDOrequest (CO_Data *d, UNS32 cobId)
UNS8 proceedPDO (CO_Data *d, Message *m)
void CopyBits (UNS8 NbBits, UNS8 *SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 *DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
Function Documentation
void CopyBits (UNS8 NbBits, UNS8 * SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 * DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
Definition at line 376 of file pdo.c.
UNS8 PDOmGR (CO_Data * d, UNS32 cobId)
Definition at line 61 of file pdo.c.
References sendPDO().
UNS8 proceedPDO (CO_Data * d, Message * m)
Definition at line 187 of file pdo.c.
References CopyBits(), getODentry(), PDOmGR(), and setODentry().
UNS8 sendPDO (CO_Data * d, s_PDO pdo, UNS8 req)
Definition at line 27 of file pdo.c.
UNS8 sendPDOrequest (CO_Data * d, UNS32 cobId)
Definition at line 154 of file pdo.c.
References sendPDO().