/home/epimerde/documents/tc11/CanFestival-3/include/pdo.h File Reference
#include <applicfg.h>
#include <def.h>
#include `data.h`
Data Structures
struct struct_s_process_var
struct struct_s_PDO
Typedefs
typedef struct_s_process_var s_process_var
typedef struct_s_PDO s_PDO
Functions
UNS8 sendPDO (CO_Data *d, s_PDO pdo, UNS8 request)
UNS8 PDOmGR (CO_Data *d, UNS32 cobId)
UNS8 buildPDO (CO_Data *d, UNS16 index)
UNS8 sendPDOrequest (CO_Data *d, UNS32 cobId)
UNS8 proceedPDO (CO_Data *d, Message *m)
UNS8 sendPDOevent (CO_Data *d, void *variable)
void CopyBits (UNS8 NbBits, UNS8 *SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 *DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
Typedef Documentation
typedef struct struct_s_PDO s_PDO
The PDO structure
typedef struct struct_s_process_var s_process_var
Function Documentation
UNS8 buildPDO (CO_Data * d, UNS16 index)
Prepare the PDO defined at index to be sent by PDOmGR Copy all the data to transmit in process_var *pwCobId : returns the value of the cobid. (subindex 1) Return 0 or 0xFF if error.
void CopyBits (UNS8 NbBits, UNS8 * SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 * DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
Definition at line 376 of file pdo.c.
References INTEGER8, and UNS8.
UNS8 PDOmGR (CO_Data * d, UNS32 cobId)
Prepare a PDO frame transmission, whose different parameters are stored in process_var table, to the slave. bus_id is hardware dependant call the function sendPDO return the result of the function sendPDO or 0xFF if error
Definition at line 61 of file pdo.c.
References struct_s_PDO::cobId, struct_s_process_var::count, struct_s_timer_entry::d, struct_s_process_var::data, struct_s_PDO::data, struct_s_PDO::len, MSG_WAR, NOT_A_REQUEST, struct_CO_Data::process_var, sendPDO(), and UNS8.
UNS8 proceedPDO (CO_Data * d, Message * m)
Compute a PDO frame reception bus_id is hardware dependant return 0xFF if error, else return 0
Definition at line 187 of file pdo.c.
References Message::cob_id, CopyBits(), struct_s_process_var::count, struct_s_timer_entry::d, Message::data, struct_s_process_var::data, struct_CO_Data::firstIndex, getODentry(), struct_CO_Data::lastIndex, Message::len, MSG_ERR, MSG_WAR, NOT_A_REQUEST, struct_CO_Data::objdict, OD_SUCCESSFUL, s_quick_index::PDO_RCV, s_quick_index::PDO_RCV_MAP, s_quick_index::PDO_TRS, s_quick_index::PDO_TRS_MAP, PDOmGR(), td_subindex::pObject, struct_CO_Data::process_var, td_indextable::pSubindex, REQUEST, setODentry(), state1, state2, state4, state5, TRANS_EVENT, TRANS_RTR, TRANS_RTR_SYNC, UNS16, UNS32, UNS8, and SHORT_CAN::w.
UNS8 sendPDO (CO_Data * d, s_PDO pdo, UNS8 request)
Transmit a PDO data frame on the bus bus_id pdo is a structure which contains the pdo to transmit bus_id is hardware dependant return canSend(bus_id,&m) or 0xFF if error request can take the value REQUEST or NOT_A_REQUEST
Definition at line 27 of file pdo.c.
References struct_CO_Data::canHandle, canSend(), Message::cob_id, struct_s_PDO::cobId, struct_s_timer_entry::d, struct_s_PDO::data, Message::data, struct_s_PDO::len, Message::len, MSG_WAR, struct_CO_Data::nodeState, NOT_A_REQUEST, Operational, REQUEST, Message::rtr, UNS8, and SHORT_CAN::w.
UNS8 sendPDOevent (CO_Data * d, void * variable)
UNS8 sendPDOrequest (CO_Data * d, UNS32 cobId)
Transmit a PDO request frame on the bus bus_id to the slave. bus_id is hardware dependant Returns 0xFF if error, other in success.
Definition at line 154 of file pdo.c.
References struct_s_PDO::cobId, struct_s_timer_entry::d, struct_CO_Data::firstIndex, struct_CO_Data::lastIndex, struct_s_PDO::len, MSG_WAR, struct_CO_Data::objdict, s_quick_index::PDO_RCV, td_subindex::pObject, td_indextable::pSubindex, REQUEST, sendPDO(), UNS16, UNS32, and UNS8.