/home/epimerde/documents/tc11/CanFestival-3/src/states.c File Reference
#include `states.h`
#include `def.h`
#include `dcf.h`
#include `nmtSlave.h`
Defines
#define StartOrStop(CommType, FuncStart, FuncStop)
#define None
Functions
void switchCommunicationState (CO_Data *d, s_state_communication *newCommunicationState)
e_nodeState getState (CO_Data *d)
void canDispatch (CO_Data *d, Message *m)
UNS8 setState (CO_Data *d, e_nodeState newState)
UNS8 getNodeId (CO_Data *d)
void setNodeId (CO_Data *d, UNS8 nodeId)
void _initialisation ()
void _preOperational ()
void _operational ()
void _stopped ()
Define Documentation
#define None
Definition at line 86 of file states.c.
#define StartOrStop(CommType, FuncStart, FuncStop)
Value:
if(newCommunicationState->CommType && !d->CurrentCommunicationState.CommType){\
                MSG_WAR(0x9999,#FuncStart, 9999);\
                d->CurrentCommunicationState.CommType = 1;\
                FuncStart;\
        }else if(!newCommunicationState->CommType && d->CurrentCommunicationState.CommType){\
                MSG_WAR(0x9999,#FuncStop, 9999);\
                d->CurrentCommunicationState.CommType = 0;\
                FuncStop;\
        }
Definition at line 76 of file states.c.
Function Documentation
void _initialisation ()
Definition at line 234 of file states.c.
void _operational ()
Definition at line 236 of file states.c.
void _preOperational ()
Definition at line 235 of file states.c.
void _stopped ()
Definition at line 237 of file states.c.
void canDispatch (CO_Data * d, Message * m)
Definition at line 39 of file states.c.
References proceedNMTstateChange(), proceedNODE_GUARD(), proceedPDO(), proceedSDO(), and proceedSYNC().
UNS8 getNodeId (CO_Data * d)
Definition at line 180 of file states.c.
e_nodeState getState (CO_Data * d)
Definition at line 33 of file states.c.
void setNodeId (CO_Data * d, UNS8 nodeId)
Definition at line 186 of file states.c.
UNS8 setState (CO_Data * d, e_nodeState newState)
Definition at line 100 of file states.c.
References decompo_dcf(), ptrTable, and switchCommunicationState().
void switchCommunicationState (CO_Data * d, s_state_communication * newCommunicationState)
Definition at line 89 of file states.c.
References heartbeatInit(), heartbeatStop(), None, resetSDO(), slaveSendBootUp(), StartOrStop, startSYNC(), and stopSYNC().