/home/epimerde/documents/tc11/CanFestival-3/src/sync.c File Reference
#include `data.h`
#include `sync.h`
#include `canfestival.h`
Functions
void SyncAlarm (CO_Data *d, UNS32 id)
UNS32 OnCOB_ID_SyncUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
void startSYNC (CO_Data *d)
void stopSYNC (CO_Data *d)
UNS8 sendSYNC (CO_Data *d, UNS32 cob_id)
UNS8 proceedSYNC (CO_Data *d, Message *m)
void _post_sync ()
void _post_TPDO ()
Function Documentation
void _post_sync ()
Definition at line 245 of file sync.c.
void _post_TPDO ()
Definition at line 246 of file sync.c.
UNS32 OnCOB_ID_SyncUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
Definition at line 43 of file sync.c.
References startSYNC().
UNS8 proceedSYNC (CO_Data * d, Message * m)
Definition at line 93 of file sync.c.
References CopyBits(), getODentry(), and PDOmGR().
UNS8 sendSYNC (CO_Data * d, UNS32 cob_id)
Definition at line 77 of file sync.c.
References proceedSYNC().
void startSYNC (CO_Data * d)
Definition at line 50 of file sync.c.
References OnCOB_ID_SyncUpdate(), RegisterSetODentryCallBack(), SetAlarm(), stopSYNC(), and SyncAlarm().
void stopSYNC (CO_Data * d)
Definition at line 71 of file sync.c.
References DelAlarm().
void SyncAlarm (CO_Data * d, UNS32 id)
Definition at line 36 of file sync.c.
References sendSYNC().