/home/epimerde/documents/tc11/CanFestival-3/drivers/timers_xeno/timers_xeno.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <native/task.h>
#include <native/timer.h>
#include <native/mutex.h>
#include <native/alarm.h>
#include `applicfg.h`
#include `can_driver.h`
#include `timer.h`
Defines
#define TIMERLOOP_TASK_CREATED 1
Functions
void cleanup_all (void)
void StopTimerLoop (void)
void EnterMutex (void)
void LeaveMutex (void)
void timerloop_task_proc (void *arg)
void StartTimerLoop (TimerCallback_t init_callback)
void CreateReceiveTask (CAN_PORT fd0, TASK_HANDLE *ReceiveLoop_task, void *ReceiveLoop_task_proc)
void WaitReceiveTaskEnd (TASK_HANDLE *Thread)
void setTimer (TIMEVAL value)
TIMEVAL getElapsedTime (void)
Variables
RT_MUTEX CanFestival_mutex
RT_TASK timerloop_task
RTIME last_time_read
RTIME last_occured_alarm
RTIME last_alarm_set
char stop_timer = 0
Define Documentation
#define TIMERLOOP_TASK_CREATED 1
Definition at line 14 of file timers_xeno.c.
Function Documentation
void cleanup_all (void)
Definition at line 24 of file timers_xeno.c.
References timerloop_task.
void CreateReceiveTask (CAN_PORT fd0, TASK_HANDLE * ReceiveLoop_task, void * ReceiveLoop_task_proc)
Definition at line 93 of file timers_xeno.c.
void EnterMutex (void)
Definition at line 35 of file timers_xeno.c.
References CanFestival_mutex.
TIMEVAL getElapsedTime (void)
Definition at line 128 of file timers_xeno.c.
References last_occured_alarm, and last_time_read.
void LeaveMutex (void)
Definition at line 40 of file timers_xeno.c.
References CanFestival_mutex.
void setTimer (TIMEVAL value)
Definition at line 122 of file timers_xeno.c.
References last_alarm_set, last_time_read, timerloop_task, and TIMEVAL_MAX.
void StartTimerLoop (TimerCallback_t init_callback)
Definition at line 60 of file timers_xeno.c.
References cleanup_all(), getElapsedTime(), last_alarm_set, last_occured_alarm, last_time_read, SetAlarm(), stop_timer, timerloop_task, and timerloop_task_proc().
void StopTimerLoop (void)
Definition at line 28 of file timers_xeno.c.
References stop_timer, and timerloop_task.
void timerloop_task_proc (void * arg)
Definition at line 45 of file timers_xeno.c.
References EnterMutex(), last_alarm_set, last_occured_alarm, LeaveMutex(), stop_timer, and TimeDispatch().
void WaitReceiveTaskEnd (TASK_HANDLE * Thread)
Definition at line 117 of file timers_xeno.c.
Variable Documentation
RT_MUTEX CanFestival_mutex
Definition at line 16 of file timers_xeno.c.
RTIME last_alarm_set
Definition at line 20 of file timers_xeno.c.
RTIME last_occured_alarm
Definition at line 19 of file timers_xeno.c.
RTIME last_time_read
Definition at line 18 of file timers_xeno.c.
char stop_timer = 0
Definition at line 22 of file timers_xeno.c.
RT_TASK timerloop_task
Definition at line 17 of file timers_xeno.c.