/home/epimerde/documents/tc11/CanFestival-3/drivers/win32/timers_win32.cpp File Reference
#include <windows.h>
#include <stdlib.h>
#include `applicfg.h`
#include `can_driver.h`
#include `timer.h`
#include `timers_driver.h`
Data Structures
class ccritical_section
class class_timers
Functions
void EnterMutex (void)
void LeaveMutex (void)
void CreateReceiveTask (CAN_HANDLE fd0, TASK_HANDLE *Thread, void *ReceiveLoopPtr)
void WaitReceiveTaskEnd (TASK_HANDLE Thread)
void StartTimerLoop (TimerCallback_t init_callback)
void StopTimerLoop (void)
void setTimer (TIMEVAL value)
TIMEVAL getElapsedTime (void)
Function Documentation
void CreateReceiveTask (CAN_HANDLE fd0, TASK_HANDLE * Thread, void * ReceiveLoopPtr)
Definition at line 78 of file timers_win32.cpp.
void EnterMutex (void)
Definition at line 64 of file timers_win32.cpp.
References CanFestival_mutex, and ccritical_section::enter().
TIMEVAL getElapsedTime (void)
Definition at line 238 of file timers_win32.cpp.
References class_timers::get_elapsed_time(), IO_PORTS_16, and TC4H.
void LeaveMutex (void)
Definition at line 69 of file timers_win32.cpp.
References CanFestival_mutex, and ccritical_section::leave().
void setTimer (TIMEVAL value)
Definition at line 233 of file timers_win32.cpp.
References maxval, class_timers::set_timer(), and timer.
void StartTimerLoop (TimerCallback_t init_callback)
Definition at line 219 of file timers_win32.cpp.
References EnterMutex(), initTimer(), LeaveMutex(), class_timers::resume_timer_thread(), SetAlarm(), class_timers::start_timer_thread(), and TIMEVAL.
void StopTimerLoop (void)
Definition at line 228 of file timers_win32.cpp.
References EnterMutex(), LeaveMutex(), class_timers::stop_timer_thread(), and timer.
void WaitReceiveTaskEnd (TASK_HANDLE Thread)
Definition at line 84 of file timers_win32.cpp.