/home/epimerde/documents/tc11/CanFestival-3/include/timers_driver.h File Reference
#include `timerscfg.h`
#include `timer.h`
Functions
void EnterMutex (void)
void LeaveMutex (void)
void WaitReceiveTaskEnd (TASK_HANDLE)
void StartTimerLoop (TimerCallback_t init_callback)
void StopTimerLoop (void)
void CreateReceiveTask (CAN_PORT, TASK_HANDLE *, void *)
Function Documentation
void CreateReceiveTask (CAN_PORT, TASK_HANDLE *, void *)
Definition at line 71 of file timers_unix.c.
void EnterMutex (void)
Definition at line 20 of file timers_unix.c.
References CanFestival_mutex, and ccritical_section::enter().
void LeaveMutex (void)
Definition at line 25 of file timers_unix.c.
References CanFestival_mutex, and ccritical_section::leave().
void StartTimerLoop (TimerCallback_t init_callback)
Definition at line 62 of file timers_unix.c.
References EnterMutex(), initTimer(), LeaveMutex(), class_timers::resume_timer_thread(), SetAlarm(), class_timers::start_timer_thread(), and TIMEVAL.
void StopTimerLoop (void)
Definition at line 55 of file timers_unix.c.
References EnterMutex(), LeaveMutex(), class_timers::stop_timer_thread(), and timer.
void WaitReceiveTaskEnd (TASK_HANDLE)
Definition at line 76 of file timers_unix.c.