/home/epimerde/documents/tc11/CanFestival-3/include/timer.h File Reference
#include <timerscfg.h>
#include <applicfg.h>
#include `data.h`
Data Structures
struct struct_s_timer_entry
Defines
#define TIMER_HANDLE INTEGER16
Typedefs
typedef void(*) TimerCallback_t (CO_Data *d, UNS32 id)
typedef struct_s_timer_entry s_timer_entry
Functions
TIMER_HANDLE SetAlarm (CO_Data *d, UNS32 id, TimerCallback_t callback, TIMEVAL value, TIMEVAL period)
TIMER_HANDLE DelAlarm (TIMER_HANDLE handle)
void TimeDispatch (void)
void setTimer (TIMEVAL value)
TIMEVAL getElapsedTime (void)
Define Documentation
#define TIMER_HANDLE INTEGER16
Definition at line 29 of file timer.h.
Typedef Documentation
typedef struct struct_s_timer_entry s_timer_entry
Definition at line 52 of file timer.h.
typedef void(*) TimerCallback_t(CO_Data *d, UNS32 id)
Definition at line 41 of file timer.h.
Function Documentation
TIMER_HANDLE DelAlarm (TIMER_HANDLE handle)
Definition at line 87 of file timer.c.
References last_timer_raw, MSG_WAR, struct_s_timer_entry::state, and timers.
TIMEVAL getElapsedTime (void)
Definition at line 66 of file canOpenDriver.c.
References class_timers::get_elapsed_time(), IO_PORTS_16, and TC4H.
TIMER_HANDLE SetAlarm (CO_Data * d, UNS32 id, TimerCallback_t callback, TIMEVAL value, TIMEVAL period)
Definition at line 38 of file timer.c.
References struct_s_timer_entry::d, last_timer_raw, MAX_NB_TIMER, TIMER_HANDLE, and timers.
void setTimer (TIMEVAL value)
Definition at line 83 of file timers_unix.c.
References maxval, class_timers::set_timer(), and timer.
void TimeDispatch (void)
Definition at line 104 of file timer.c.
References getElapsedTime(), last_timer_raw, min_val, TIMER_HANDLE, timers, TIMEVAL, TIMEVAL_MAX, and total_sleep_time.