/home/epimerde/documents/tc11/CanFestival-3/include/win32/canfestival.h File Reference
#include `timerscfg.h`
#include `can_driver.h`
#include `data.h`
#include <windows.h>
Typedefs
typedef HINSTANCE LIB_HANDLE
Functions
UNS8 UnLoadCanDriver (LIB_HANDLE handle)
LIB_HANDLE LoadCanDriver (char *driver_name)
UNS8 canSend (CAN_PORT port, Message *m)
CAN_PORT canOpen (s_BOARD *board, CO_Data *d)
int canClose (CO_Data *d)
Typedef Documentation
typedef HINSTANCE LIB_HANDLE
Definition at line 31 of file canfestival.h.
Function Documentation
int canClose (CO_Data * d)
Definition at line 178 of file unix.c.
References canClose(), struct_CO_Data::canHandle, driver_data::continue_receive_thread, DLL_CALL, EnterMutex(), CANPort::fd, driver_data::inst, LeaveMutex(), driver_procs::m_canClose, driver_data::receive_thread, CANPort::receiveTask, s_driver_procs, and WaitReceiveTaskEnd().
CAN_PORT canOpen (s_BOARD * board, CO_Data * d)
Definition at line 145 of file unix.c.
References struct_s_BOARD::baudrate, struct_s_BOARD::busname, struct_CO_Data::canHandle, canOpen(), canports, canReceiveLoop(), driver_data::continue_receive_thread, CreateReceiveTask(), driver_data::d, CANPort::d, DLL_CALL, EnterMutex(), CANPort::fd, driver_data::inst, LeaveMutex(), driver_procs::m_canOpen, MAX_NB_CAN_PORTS, driver_data::receive_thread, s_driver_procs, and CANPort::used.
UNS8 canSend (CAN_PORT port, Message * m)
Definition at line 120 of file unix.c.
References canSend(), DLL_CALL, EnterMutex(), driver_data::inst, LeaveMutex(), driver_procs::m_canSend, s_driver_procs, and UNS8.
LIB_HANDLE LoadCanDriver (char * driver_name)
Definition at line 84 of file unix.c.
References canClose(), canOpen(), canReceive(), canSend(), DLSYM, driver_procs::load_canfestival_driver(), and s_driver_procs.
UNS8 UnLoadCanDriver (LIB_HANDLE handle)
Definition at line 71 of file unix.c.