
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVEDIC_H
#define SLAVEDIC_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 slavedic_valueRangeTest (UNS8 typeValue, void * value);
const indextable * slavedic_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data slavedic_Data;
extern UNS32 counter;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 position;		/* Mapped at index 0x2001, subindex 0x00*/

#endif // SLAVEDIC_H
